---
name: actions-template-sync

permissions: read-all

on: # yamllint disable-line rule:truthy
  # cronjob trigger At 00:00 on day-of-month 1. https://crontab.guru/every-month
  schedule:
    - cron: "0 0 1 * *"
  # manual trigger
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@8ec19a5f2721ffb81ff809aa340ddf75e6a85ea6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: mihaur/node-fastify-template
          upstream_branch: main # defaults to main
